Branch test
DanyloBobrivnyk/web-services pull request #1
Opened 2020-10-19 12:11 UTC by DanyloBobrivnyk

2020-10-26 13:15 UTC, DanyloBobrivnyk commented
Pull request for web-services lecture.
Kindly asking to check it out ;)

2020-10-26 13:17 UTC, DanyloBobrivnyk commented on express.js
> +})
Comment test for home page func

2020-10-26 16:24 UTC, Lervana requested changes
You have "node_modules" commited, to fix it:

- Delete the node_modules folder on the computer
- Make commit with these changes (deletion of these files) as new commit
- Add the .gitignore file with the line "/ node_modules"
- Push changes to the github
- Use the npm command to install node_modules

2020-10-27 17:09 UTC, Lervana approved these changes

2020-10-27 17:10 UTC, Lervana approved these changes

2020-10-27 17:11 UTC, merged